environment: {}
parameters: {}
packages:
  - name: test-triggers
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello1
        web: false
        triggers:
          - name: invoke1
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"
              withBody:
                name: tester
      - name: hello2
        web: false
        triggers:
          - name: invoke2
            sourceType: scheduler
            enabled: false
            sourceDetails:
              cron: "30 * * * *"
