name: Test Doctl Sandbox

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        go-version: [ 1.17.x ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    concurrency: doctl_sandbox_tests

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout doctl-sandbox-plugin
      uses: actions/checkout@v3
      with:
        path: doctl-sandbox-plugin

    - name: Checkout doctl
      uses: actions/checkout@v3
      with:
        repository: digitalocean/doctl
        ref: feature/sandbox
        path: doctl

    - name: Build doctl
      run: ./doctl-extras/buildOne.sh
      working-directory: doctl-sandbox-plugin
      
    - name: Initialize doctl default context
      run: ./builds/doctl auth init --access-token ${{ secrets.TEST_DO_TOKEN }}
      working-directory: doctl
      
    - name: Test install, connect, and upgrade
      run: ../doctl-sandbox-plugin/testInstallation.sh
      working-directory: doctl

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'

    - name: Install dependencies for bats testing
      run: npm install
      working-directory: doctl-sandbox-plugin/tests
      
    - name: Test functionality via bats
      run: npm test
      working-directory: doctl-sandbox-plugin/tests
