name: Upload new sandbox tarball

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout doctl-sandbox-plugin
      uses: actions/checkout@v3
      with:
        path: doctl-sandbox-plugin
      
    - name: Run upload script
      run: ./package.sh
      working-directory: doctl-sandbox-plugin
