name: Upload new sandbox tarball

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout doctl-sandbox-plugin
      uses: actions/checkout@v3
      with:
        path: doctl-sandbox-plugin
        
    - name: set AWS credentials for profile 'do'
      run: |
        aws --profile do configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws --profile do configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws --profile do configure set region us-east1
        aws configure list-profiles
        aws --profile do configure list    
      
    - name: Run upload script
      run: ./package.sh
      working-directory: doctl-sandbox-plugin
